version: '3'
services:
  auth_api:
    build: ./auth_api
    volumes:
      - ./auth_api:/auth_api
    ports:
      - "8083:8083"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - redis
      - auth_db
    restart: always

  auth_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./auth_db/db_data:/var/lib/mysql
      - ./auth_db/my.conf:/etc/mysql/conf.d/my.conf
    security_opt:
      - seccomp:unconfined

  flask_api_one:
    build: ./flask_api_one
    ports:
      - "5000:5000"
    volumes:
      - ./flask_api_one:/usr/src/flask_api_one
    depends_on:
      - redis

  flask_api_two:
    build: ./flask_api_two
    ports:
      - "6000:6000"
    volumes:
      - ./flask_api_two:/usr/src/flask_api_two
    depends_on:
      - redis

  bff_api:
    build: ./bff_api
    volumes:
      - ./bff_api:/bff_api
    ports:
      - "8082:8082"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:4
